name: Deploy to github pages

on:
  push:
    tags: 
    - '*'

jobs:
  deploy_to_github_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      # install nodejs
      - name: install nodejs
        uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: install dependencies
        run: npm i
      - name: build project files
        run: npm run build
      
      # deploy
      - name: deploy to github pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
